### ISSUE TITLE
TypeError: element.scrollToFixed is not a function

### ISSUE THREAD

**Issue by kyawmyintthein** [xavierdutreilh/angular-scrolltofixed#1]
![screen shot 2015-10-07 at 12 00 58 pm](https://cloud.githubusercontent.com/assets/3658706/10328778/2b261f5a-6ceb-11e5-8208-7bd42fa1a07f.png)
![screen shot 2015-10-07 at 12 02 01 pm](https://cloud.githubusercontent.com/assets/3658706/10328785/42a3eff4-6ceb-11e5-98af-b9956f4e5bac.png)

**Comment by xavierdutreilh** [comment]
Hi @kyawmyintthein, can you provide the list of scripts in your HTML page?

This error seems to indicate that ScrollToFixed has not been loaded.

**Comment by xavierdutreilh** [comment]
In addition, I have pushed a code sample in d71674913ae4a9fb3512f8e580701f78fbc95e94. It tells you in which order scripts should be loaded (jquery, scrolltofixed, then angular, and angular-scrolltofixed).

If you need to test the code sample, you can `git clone` the repository, then run `npm install` and open `example1.html` in your web browser.

**Comment by kyawmyintthein** [comment]
Thanks @xavierdutreilh , I found the problem because of I haven't install "ScrollToFixed" JQuery lib.

**Comment by xavierdutreilh** [comment]
OK, I am glad that was the issue.
