### ISSUE TITLE
How to trigger events?

### ISSUE THREAD

**Issue by apokyro** [xavierdutreilh/angular-scrolltofixed#2]
Hi, great directive! It works perfect!

I want to trigger an update event to fixed element when user clicks a button. How to do that?

Thanks in advance.

p.s. The button has a .click event with jQuery inside a $scope.

**Comment by xavierdutreilh** [comment]
Hi, @apokyro.

First, you need to find the fixed element in your click handler, then, use the `trigger` function to send an `update` event .

For example, if you clone the repository, and open example1.html into your web browser, you can run this piece of code in the web console to achieve this goal:
```javascript
// find the fixed element
var element = angular.element('[scroll-to-fixed]');
// trigger the update event
element.trigger('update');
```

You can also find other examples on how to trigger events in the test suite. In particular, here: https://github.com/xavierdutreilh/angular-scrolltofixed/blob/master/test/scrollToFixed_test.js#L86

**Comment by apokyro** [comment]
Hi, @xavierdutreilh 

You helped me a lot. Thank you very much!

One last thing. What about having two fixed elements on the same page and want to trigger an event to one of them? How to determine which is which?

Thanks again.

**Comment by xavierdutreilh** [comment]
@apokyro, probably that you use two different markups? For instance:
```html
<header scroll-to-fixed>MY FIXED HEADER</header>
...
<footer scroll-to-fixed>MY FIXED FOOTER</footer>
```

In this case, you would target the fixed header with a more specific selector: `header[scroll-to-fixed]`.

You can also find another example with two fixed elements in the [official demo](http://bigspotteddog.github.io/ScrollToFixed/). In it, you would target the fixed header with `.header`.

**Comment by apokyro** [comment]
Alright, thank you!
